name: Integration test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A test job
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test action step
        uses: ./
        id: test
        with:
          # Triggers
          host: 'git.rwth-aachen.de'
          trigger_token: ${{ secrets.DEPLOY_MONTIVERSE_TRIGGER_TOKEN  }}
          # not needed for public repos
          access_token: ${{ secrets.DEPLOY_MONTIVERSE_ACCESS_TOKEN  }}
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          id: '91803'
          ref: 'main'
          variables: '{}'
      - name: Get the output status
        run: echo "The status was ${{ steps.test.outputs.status }}"
      - name: Get the output web_url
        run: echo "The web_url was ${{ steps.test.outputs.web_url }}"
      - name: Get the output pretty_output
        run: echo "${steps.test.outputs.pretty_output}}" >> $GITHUB_STEP_SUMMARY
      - name: Create commit comment
        uses: peter-evans/commit-comment@v3
        with:
          body: ${{steps.test.outputs.pretty_output}}
          reactions: '+1'

