on: [push]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test action step
        uses: ./
        id: test
        with:
          host: 'gitlab.tugraz.at'
          token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          id: '21238'
          ref: 'main'
          variables: '{"UPSTREAM_PROJECT_PATH":"dbp/dispatch/dispatch","UPSTREAM_COMMIT_BRANCH":"${{ github.ref_name }}","UPSTREAM_COMMIT_SHA":"${{ github.ref_name }}"}'
      - name: Get the output status
        run: echo "The status was ${{ steps.test.outputs.status }}"
