name: Integration test
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  workflow_dispatch:

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: A test job
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test action step
        uses: ./
        id: test
        with:
          # Triggers https://gitlab.com/digital-blueprint/gitlab-pipeline-trigger-action-example/-/pipelines
          host: 'gitlab.com'
          trigger_token: ${{ secrets.DEPLOY_TRIGGER_TOKEN }}
          # not needed for public repos
          #access_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          id: '44347238'
          ref: 'main'
          variables: '{"VAR1":"value1","VAR2":"value2"}'
      - name: Get the output status
        run: echo "The status was ${{ steps.test.outputs.status }}"
